name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - feature/convert-black-white

jobs:
  build:
    name: Build & Test Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          go mod tidy
          cd frontend && npm install

      - name: Build Docker Image
        run: |
          docker build -t photoprism-app .

      - name: Run Tests Inside Container
        run: |
          docker run --rm photoprism-app make test-js
          docker run --rm photoprism-app go test ./internal/... -v

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to DockerHub
        run: |
          docker tag photoprism-app hayahussienn/photoprism-app:${{ github.run_number }}
          docker push hayahussienn/photoprism-app:${{ github.run_number }}
