name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - feature/convert-black-white

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Run JavaScript Tests (make test-js)
        run: |
          make test-js
