name: Unittests

on:
  push:
    branches:
      - develop
      - feature/convert-black-white

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Run JavaScript Tests
        run: |
          make test-js

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Version
        run: echo "VERSION=0.0.1" >> $GITHUB_ENV

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false  # Build only, scan before pushing
          tags: hayahussienn/photoprism-app:${{ env.VERSION }}

      - name: Scan Image with Docker Scout  # ✅ Security Check
        run: |
          docker scout quickview hayahussienn/photoprism-app:${{ env.VERSION }}
        continue-on-error: true  # Prevent failing workflow due to vulnerabilities


      - name: Always Push Docker Image  # ✅ Ensures push even if scan fails
        run: |
          docker push hayahussienn/photoprism-app:${{ env.VERSION }}
