name: Unittests, Checkstyle, and Docker Build

on:
  push:
    branches:
      - develop
      - feature/convert-black-white

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
          golangci-lint --version

      - name: Run Go Lint
        run: golangci-lint run ./... --timeout=10m

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Run ESLint
        run: |
          cd frontend
          npx eslint . --quiet

      - name: Set Dynamic Version
        run: echo "VERSION=0.0.2-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: hayahussienn/photoprism-app:${{ env.VERSION }}
